# Generated by Django 5.1.4 on 2025-02-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Biens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('dimension', models.CharField(max_length=10)),
                ('quartier', models.CharField(max_length=100)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lagitude', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biens.categories')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
    ]
