# Generated by Django 5.1.4 on 2025-02-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biens',
            options={'ordering': ['-date_operateur_ajout']},
        ),
        migrations.RenameField(
            model_name='biens',
            old_name='quartier',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='biens',
            old_name='date_ajout',
            new_name='date_operateur_ajout',
        ),
        migrations.RenameField(
            model_name='biens',
            old_name='auteur',
            new_name='proprietaire',
        ),
        migrations.RenameField(
            model_name='biens',
            old_name='category',
            new_name='type',
        ),
        migrations.AddField(
            model_name='biens',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='PDF'),
        ),
    ]
