# Generated by Django 5.1.4 on 2025-02-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0003_alter_biens_lagitude_alter_biens_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biens',
            old_name='lagitude',
            new_name='latitude',
        ),
    ]
