# Generated by Django 5.1.4 on 2025-02-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0004_rename_lagitude_biens_latitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
