# Generated by Django 5.1.4 on 2025-03-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0006_biens_date_operateur_modification_biens_modifie_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='date_operateur_ajout',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='biens',
            name='date_operateur_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
