# Generated by Django 5.1.4 on 2025-03-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0008_alter_biens_date_operateur_ajout'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens',
            name='date_operateur_supprimer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
