# Generated by Django 5.1.4 on 2025-03-22 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0010_biens_est_supprimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='date_operateur_supprimer',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
