# Generated by Django 5.1.4 on 2025-03-23 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0018_alter_biens_date_operateur_supprimer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biens',
            name='date_operateur_supprimer',
        ),
    ]
