# Generated by Django 5.1.4 on 2025-03-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0019_remove_biens_date_operateur_supprimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='biens',
            name='date_operateur_supprimer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
