# Generated by Django 5.1.4 on 2025-03-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biens', '0022_alter_biens_date_operateur_supprimer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biens',
            name='date_operateur_supprimer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
