# Generated by Django 5.1.4 on 2025-02-14 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='etat_connecxion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
