# Generated by Django 5.1.4 on 2025-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0002_profile_etat_connecxion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
