# Generated by Django 5.1.4 on 2025-02-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0004_alter_profile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
