# Generated by Django 5.1.4 on 2025-02-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0005_profile_date_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_seen',
        ),
    ]
