# Generated by Django 5.1.4 on 2025-03-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0006_remove_profile_date_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='etat_connecxion',
            new_name='etat_connexion',
        ),
    ]
